// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pelagonher.Api.Data;

#nullable disable

namespace Pelagonher.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602003544_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pelagonher.Api.Models.Alumno", b =>
                {
                    b.Property<int>("ID_ALUMNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_ALUMNO"));

                    b.Property<string>("APELLIDO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CORREO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ID_CURSO")
                        .HasColumnType("int");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_ALUMNO");

                    b.HasIndex("ID_CURSO");

                    b.ToTable("ALUMNOS");
                });

            modelBuilder.Entity("Pelagonher.Api.Models.Curso", b =>
                {
                    b.Property<int>("ID_CURSO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_CURSO"));

                    b.Property<string>("DESCRIPCION_CURSO")
                        .HasColumnType("longtext");

                    b.Property<string>("DURACION")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FECHA_INICIO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NOMBRE_CURSO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID_CURSO");

                    b.ToTable("CURSOS");
                });

            modelBuilder.Entity("Pelagonher.Api.Models.Alumno", b =>
                {
                    b.HasOne("Pelagonher.Api.Models.Curso", "Curso")
                        .WithMany("Alumnos")
                        .HasForeignKey("ID_CURSO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Pelagonher.Api.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
